export const CHANGE_TEXT_FIELD = 'CHANGE_TEXT_FIELD';

export const UPDATE_TODO_ARRAY = 'UPDATE_TODO_ARRAY';

export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const DELETE_TODO = 'DELETE_TODO'